name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4.2.2
    - run: rustup update
    - run: cargo build --release
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        name: ${{ matrix.os }}-artifact
        path: |
          target/release/ssg.exe
          target/release/ssg
